In [1]:
import numpy as np

In [2]:
lst = [1,2,3,4,5,6]

In [5]:
type(lst)

list

In [7]:
type(arr)

numpy.ndarray

In [8]:
arr.ndim

1

In [20]:
arr  = np.array([1,2,3,4,5,6])

In [17]:
arr

array(['1', '2', '3', '4', '5', '6', '7.0', 'a'], dtype='<U32')

In [18]:
arr.dtype

dtype('<U32')

In [21]:
arr.shape

(6,)

In [29]:
arr2 = np.array(list(range(1,21)))

In [30]:
arr2

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [31]:
arr[1:10:2]

array([2, 4, 6])

In [32]:
lst3 = [[1,2,3,4,5,6],[7,8,9,5,6,9]]

In [33]:
lst3

[[1, 2, 3, 4, 5, 6], [7, 8, 9, 5, 6, 9]]

In [34]:
arr = np.array(lst3)

In [35]:
arr

array([[1, 2, 3, 4, 5, 6],
       [7, 8, 9, 5, 6, 9]])

In [36]:
arr.ndim

2

In [37]:
arr.shape

(2, 6)

In [39]:
arr.size

12

In [40]:
arr.dtype

dtype('int32')

In [43]:
np.array([1,np.nan]).dtype

dtype('float64')

In [44]:
arr

array([[1, 2, 3, 4, 5, 6],
       [7, 8, 9, 5, 6, 9]])

In [45]:
[row_starting : row ending point : row steping point  ,    columns starting : columns ending point :]

arr[]

8

In [46]:
arr[1]

8

In [48]:
arr[1:2,1:2]

array([[8]])

In [ ]:
0,1,2,3,4,5,6,7,8

In [51]:
ar = np.arange(20)
ar

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [53]:
zero = np.zeros(20)
zero

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0.])

In [58]:
zero = np.zeros((20,5))
zero

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [59]:
np.ones((2,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [61]:
np.linspace(1,10,10)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [64]:
np.arange(60).reshape(15,4)  

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31],
       [32, 33, 34, 35],
       [36, 37, 38, 39],
       [40, 41, 42, 43],
       [44, 45, 46, 47],
       [48, 49, 50, 51],
       [52, 53, 54, 55],
       [56, 57, 58, 59]])

In [67]:
arr = np.arange(60).reshape(15,4)  
arr


array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31],
       [32, 33, 34, 35],
       [36, 37, 38, 39],
       [40, 41, 42, 43],
       [44, 45, 46, 47],
       [48, 49, 50, 51],
       [52, 53, 54, 55],
       [56, 57, 58, 59]])

In [69]:
arr.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59])

In [70]:
arr.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59])

In [71]:
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31],
       [32, 33, 34, 35],
       [36, 37, 38, 39],
       [40, 41, 42, 43],
       [44, 45, 46, 47],
       [48, 49, 50, 51],
       [52, 53, 54, 55],
       [56, 57, 58, 59]])

In [75]:
arr.shape

(15, 4)

In [78]:
arr.T.shape

(4, 15)

In [79]:
np.random.randint(1,5,9)

array([2, 2, 2, 3, 1, 4, 1, 4, 4])

In [80]:
np.random.random((10,5))

array([[0.36733974, 0.09012209, 0.63897625, 0.40132797, 0.05912635],
       [0.42837418, 0.41839076, 0.14444365, 0.88053322, 0.07707206],
       [0.96828655, 0.26943641, 0.29327893, 0.75111766, 0.09136968],
       [0.79012866, 0.86883636, 0.09463925, 0.75038295, 0.36290689],
       [0.76295734, 0.1770803 , 0.71606432, 0.59504943, 0.01833417],
       [0.90205459, 0.15649716, 0.27975233, 0.09252053, 0.75960675],
       [0.65267468, 0.91101022, 0.80817538, 0.53956979, 0.15483003],
       [0.696499  , 0.93637498, 0.18107794, 0.02746683, 0.72905566],
       [0.70112894, 0.45675389, 0.7259302 , 0.02716028, 0.36416914],
       [0.83897845, 0.48870406, 0.98236259, 0.27547445, 0.28863285]])

In [91]:
arr = np.arange(180).reshape((3,15,4))
arr

array([[[  0,   1,   2,   3],
        [  4,   5,   6,   7],
        [  8,   9,  10,  11],
        [ 12,  13,  14,  15],
        [ 16,  17,  18,  19],
        [ 20,  21,  22,  23],
        [ 24,  25,  26,  27],
        [ 28,  29,  30,  31],
        [ 32,  33,  34,  35],
        [ 36,  37,  38,  39],
        [ 40,  41,  42,  43],
        [ 44,  45,  46,  47],
        [ 48,  49,  50,  51],
        [ 52,  53,  54,  55],
        [ 56,  57,  58,  59]],

       [[ 60,  61,  62,  63],
        [ 64,  65,  66,  67],
        [ 68,  69,  70,  71],
        [ 72,  73,  74,  75],
        [ 76,  77,  78,  79],
        [ 80,  81,  82,  83],
        [ 84,  85,  86,  87],
        [ 88,  89,  90,  91],
        [ 92,  93,  94,  95],
        [ 96,  97,  98,  99],
        [100, 101, 102, 103],
        [104, 105, 106, 107],
        [108, 109, 110, 111],
        [112, 113, 114, 115],
        [116, 117, 118, 119]],

       [[120, 121, 122, 123],
        [124, 125, 126, 127],
        [128, 129, 130, 131],
      

In [98]:
arr.shape

(3, 15, 4)

In [100]:
arr[0].shape

(15, 4)

In [ ]:
arr[table , row , column]


In [107]:
arr[-1,-1,-1]

179

In [110]:
ar1  = np.arange(10)
ar1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [112]:
ar1 * 2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])