In [1]:
import numpy as np

In [3]:
arr = np.arange(60).reshape(15,4)
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31],
       [32, 33, 34, 35],
       [36, 37, 38, 39],
       [40, 41, 42, 43],
       [44, 45, 46, 47],
       [48, 49, 50, 51],
       [52, 53, 54, 55],
       [56, 57, 58, 59]])

In [13]:
arr[-1,-1] = 'rocky'

ValueError: invalid literal for int() with base 10: 'rocky'

In [7]:
arr[5,2]

500

In [10]:
arr[0] = [10, 12, 22, 33]

In [11]:
arr

array([[ 10,  12,  22,  33],
       [  4,   5,   6,   7],
       [  8,   9,  10,  11],
       [ 12,  13,  14,  15],
       [ 16,  17,  18,  19],
       [ 20,  21, 500,  23],
       [ 24,  25,  26,  27],
       [ 28,  29,  30,  31],
       [ 32,  33,  34,  35],
       [ 36,  37,  38,  39],
       [ 40,  41,  42,  43],
       [ 44,  45,  46,  47],
       [ 48,  49,  50,  51],
       [ 52,  53,  54,  55],
       [ 56,  57,  58,  59]])

In [17]:
arr[0][::-1]

array([33, 22, 12, 10])

In [18]:
name = 'jaipur'

In [19]:
name[::-1]

'rupiaj'

In [21]:
a = list(range(10))
a

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [22]:
a[::-1]

[9, 8, 7, 6, 5, 4, 3, 2, 1, 0]

In [24]:
np.min(arr)

4

In [26]:
np.max(arr[0])


33

In [27]:
np.sum(arr)

2319

In [28]:
np.mean(arr)

38.65

In [30]:
arr.sort()

In [32]:
arr

array([[ 10,  12,  22,  33],
       [  4,   5,   6,   7],
       [  8,   9,  10,  11],
       [ 12,  13,  14,  15],
       [ 16,  17,  18,  19],
       [ 20,  21,  23, 500],
       [ 24,  25,  26,  27],
       [ 28,  29,  30,  31],
       [ 32,  33,  34,  35],
       [ 36,  37,  38,  39],
       [ 40,  41,  42,  43],
       [ 44,  45,  46,  47],
       [ 48,  49,  50,  51],
       [ 52,  53,  54,  55],
       [ 56,  57,  58,  59]])

In [ ]:
arr.dtype

In [49]:
arr2 =  np.array([2,5,10,2])
arr2

array([ 2,  5, 10,  2])

In [53]:
arr.shape

(15, 4)

In [54]:
arr2 = arr

In [55]:
arr2

array([[ 10,  12,  22,  33],
       [  4,   5,   6,   7],
       [  8,   9,  10,  11],
       [ 12,  13,  14,  15],
       [ 16,  17,  18,  19],
       [ 20,  21,  23, 500],
       [ 24,  25,  26,  27],
       [ 28,  29,  30,  31],
       [ 32,  33,  34,  35],
       [ 36,  37,  38,  39],
       [ 40,  41,  42,  43],
       [ 44,  45,  46,  47],
       [ 48,  49,  50,  51],
       [ 52,  53,  54,  55],
       [ 56,  57,  58,  59]])

In [56]:
arr+ arr2

array([[  20,   24,   44,   66],
       [   8,   10,   12,   14],
       [  16,   18,   20,   22],
       [  24,   26,   28,   30],
       [  32,   34,   36,   38],
       [  40,   42,   46, 1000],
       [  48,   50,   52,   54],
       [  56,   58,   60,   62],
       [  64,   66,   68,   70],
       [  72,   74,   76,   78],
       [  80,   82,   84,   86],
       [  88,   90,   92,   94],
       [  96,   98,  100,  102],
       [ 104,  106,  108,  110],
       [ 112,  114,  116,  118]])

In [ ]:
pip install matplotlib